In [390]:
import csv
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity

In [391]:
dataUser = pd.read_csv('UserCentreInteret.csv') #Les données de l'utilisateur
dataInfluencer = pd.read_csv('influencersFitness.csv') #Liste des influenceurs qui présente l'intérêt de cet utilisateur 




In [392]:
dataInfluencer #on peut remarquer que le score n'est pas encore calculé

alias            username  \
0           Tiboinshape         tiboinshape   
1             𝗔 𝗬 𝗢 𝗨 𝗕        ayoub_dhouib   
2  Jeremy Scott Fitness  jeremyscottfitness   
3              MankoFit         massy.arias   
4          Alexia Clark        alexia_clark   
5       MAMAN FITCATS 🐱         jujufitcats   
6       Jay T. Maryniak             jtm_fit   
7      Jeanette Jenkins   msjeanettejenkins   
8               Shaun T              shaunt   

                                                 bio  followers__count  \
0  DAAMN la #TeamShape\n🎥Youtube: tiboinshape\n👻S...           2893685   
1  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
2  Jeremy Scott Fitness Podcast🔥\nBest Selling Au...            287574   
3                      Health coach @mawarriors CEO            2603731   
4  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
5  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
6  NEW YORK Creator of The Functional Method  I h...            566898   
7  Turn on post notifications 28yrs Experience Tr...            555090   
8  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  e_xma maximettr72 elodie.bonnet.79 thomaslesav...   
1  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
2  bodyforlife_ jromero_3433 lula_1127 konstantin...   
3  bayujovi2 beardedbarbellmaintenance kvillalba5...   
4  marti_m87 hatandhoopsfitness drlozanoorella ia...   
5  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
6  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
7  cbarbour3 alexanderfinley01 gergoerous_being b...   
8  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption  Score  
0  #teamshape #fitgirl #teamshape #teamshape #tea...    NaN  
1  #healthylifestyle #fitness #foodography #worko...    NaN  
2  #jeremyscottfitness #fitfam #fitness #health #...    NaN  
3  #ma60day #momlife #childofGod #goku #mawarrior...    NaN  
4  #queenofworkouts #fitness #fitforHisreason #pr...    NaN  
5  #teamfitcats #jujufitcats #teamshape #crossfit...    NaN  
6  #legday #functionaltraining #bodybuilding #bod...    NaN  
7  #HealthyEating #Stretches #BackStretches #Tota...    NaN  
8   #INSANITY  #trustandbelievepod #twins #twinsa...    NaN

## Critère 1 : Influenceurs qui sont estimés similaires à des influenceurs suivis par l’utilisateur u

In [393]:
#on va chercher les influenceurs qui sont déjà suivis par l'utilisateur u en calculant la distance de similarité entre 
#la liste des followings de l'utilisateur et la liste des influenceurs à recommander 

followingUser = dataUser["Following"] #la liste des followings

distanceFollowersFollowing = [] #array pour stocker les distances entre les followings de u et chaque influenceur de la liste
                                #à recommander
    
vec = CountVectorizer() #Convert a collection of text documents to a matrix of token counts

k = []
k.append(followingUser[0])
f = vec.fit_transform(k).todense()

index=0
listInf = dataInfluencer["username"] #Liste des usernames des influenceurs à recommander

#On parcoure la liste et on calcule à chaque fois la distance de similarité entre username de l'influenceur i et la liste
#des following de l'utilisateur u


while index<len(dataInfluencer):
    c = []
    c.append(listInf[index])
    f1 = vec.transform(c).todense()
    distanceFollowersFollowin.append(cosine_similarity(f,f1))
    index+=1

distanceFollowersFollowin #afficher ces distances

#On peut remarquer que le premier et le 3ème influenceur présente une distance non nulle ce qui prouve
#que ces influenceurs sont déjà suivis par l'utilisateur u

[array([[0.04472136]]),
 array([[0.]]),
 array([[0.04472136]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]]),
 array([[0.]])]

In [394]:
a = [] #array pour stocker les indices des influenceurs déjà suivis

i = 0 
while i<len(distanceFollowersFollowin):
    if (distanceFollowersFollowin[i][0][0]!= 0):
        a.append(i)
    i+=1
    
#Maintenant on parcoure la liste des influenceurs à recommander différents des influenceurs déjà suivis 
#et on calcule leurs distances de similarité avec ces derniers
#pour chaque influenceur à recommander on ajoute sa distance de similarité avec les influenceurs déjà suivis à son score
index1=0
while index1<len(a):
    ve = CountVectorizer()
    c = []
    c.append(dataInfluencer["posts__caption"][ a[index1] ])
    f = ve.fit_transform(c).todense()
    index2 = 0
    while index2<len(dataInfluencer):
        if (index2 == a[index1] ):
            dataInfluencer["Score"][index2] = 0
        if (dataInfluencer["Score"][index2] !=0 ):    
            k= []
            k.append(dataInfluencer["posts__caption"][index2])
            f1 = ve.transform(k).todense()
            d = cosine_similarity(f,f1)
            dataInfluencer["Score"][index2] = d   
        index2+=1
    index1+=1
 


C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a D

In [395]:
dataInfluencer.head(10)

alias            username  \
0           Tiboinshape         tiboinshape   
1             𝗔 𝗬 𝗢 𝗨 𝗕        ayoub_dhouib   
2  Jeremy Scott Fitness  jeremyscottfitness   
3              MankoFit         massy.arias   
4          Alexia Clark        alexia_clark   
5       MAMAN FITCATS 🐱         jujufitcats   
6       Jay T. Maryniak             jtm_fit   
7      Jeanette Jenkins   msjeanettejenkins   
8               Shaun T              shaunt   

                                                 bio  followers__count  \
0  DAAMN la #TeamShape\n🎥Youtube: tiboinshape\n👻S...           2893685   
1  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
2  Jeremy Scott Fitness Podcast🔥\nBest Selling Au...            287574   
3                      Health coach @mawarriors CEO            2603731   
4  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
5  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
6  NEW YORK Creator of The Functional Method  I h...            566898   
7  Turn on post notifications 28yrs Experience Tr...            555090   
8  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  e_xma maximettr72 elodie.bonnet.79 thomaslesav...   
1  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
2  bodyforlife_ jromero_3433 lula_1127 konstantin...   
3  bayujovi2 beardedbarbellmaintenance kvillalba5...   
4  marti_m87 hatandhoopsfitness drlozanoorella ia...   
5  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
6  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
7  cbarbour3 alexanderfinley01 gergoerous_being b...   
8  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
0  #teamshape #fitgirl #teamshape #teamshape #tea...  0.000000  
1  #healthylifestyle #fitness #foodography #worko...  0.377964  
2  #jeremyscottfitness #fitfam #fitness #health #...  0.000000  
3  #ma60day #momlife #childofGod #goku #mawarrior...  0.534522  
4  #queenofworkouts #fitness #fitforHisreason #pr...  0.267261  
5  #teamfitcats #jujufitcats #teamshape #crossfit...  0.462910  
6  #legday #functionaltraining #bodybuilding #bod...  0.267261  
7  #HealthyEating #Stretches #BackStretches #Tota...  0.377964  
8   #INSANITY  #trustandbelievepod #twins #twinsa...  0.267261

In [396]:
#On élimine les influenceurs déjà suivis
i=0
while i<len(dataInfluencer):
    if (dataInfluencer['Score'][i]==0):
        dataInfluencer.drop(i,inplace=True)
    i+=1
    

In [397]:
dataInfluencer

alias           username  \
1         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   
3          MankoFit        massy.arias   
4      Alexia Clark       alexia_clark   
5   MAMAN FITCATS 🐱        jujufitcats   
6   Jay T. Maryniak            jtm_fit   
7  Jeanette Jenkins  msjeanettejenkins   
8           Shaun T             shaunt   

                                                 bio  followers__count  \
1  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
3                      Health coach @mawarriors CEO            2603731   
4  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
5  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
6  NEW YORK Creator of The Functional Method  I h...            566898   
7  Turn on post notifications 28yrs Experience Tr...            555090   
8  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
1  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
3  bayujovi2 beardedbarbellmaintenance kvillalba5...   
4  marti_m87 hatandhoopsfitness drlozanoorella ia...   
5  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
6  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
7  cbarbour3 alexanderfinley01 gergoerous_being b...   
8  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
1  #healthylifestyle #fitness #foodography #worko...  0.377964  
3  #ma60day #momlife #childofGod #goku #mawarrior...  0.534522  
4  #queenofworkouts #fitness #fitforHisreason #pr...  0.267261  
5  #teamfitcats #jujufitcats #teamshape #crossfit...  0.462910  
6  #legday #functionaltraining #bodybuilding #bod...  0.267261  
7  #HealthyEating #Stretches #BackStretches #Tota...  0.377964  
8   #INSANITY  #trustandbelievepod #twins #twinsa...  0.267261

In [401]:
#on met à jour les indices de dataset
i=0 
index = []
while i<len(dataInfluencer):
    index.append(i)
    i+=1
    
dataInfluencer.set_index([pd.Index(index)],inplace=True)

In [402]:
dataInfluencer

alias           username  \
0         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   
1          MankoFit        massy.arias   
2      Alexia Clark       alexia_clark   
3   MAMAN FITCATS 🐱        jujufitcats   
4   Jay T. Maryniak            jtm_fit   
5  Jeanette Jenkins  msjeanettejenkins   
6           Shaun T             shaunt   

                                                 bio  followers__count  \
0  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
1                      Health coach @mawarriors CEO            2603731   
2  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
3  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
4  NEW YORK Creator of The Functional Method  I h...            566898   
5  Turn on post notifications 28yrs Experience Tr...            555090   
6  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
1  bayujovi2 beardedbarbellmaintenance kvillalba5...   
2  marti_m87 hatandhoopsfitness drlozanoorella ia...   
3  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
4  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
5  cbarbour3 alexanderfinley01 gergoerous_being b...   
6  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
0  #healthylifestyle #fitness #foodography #worko...  0.377964  
1  #ma60day #momlife #childofGod #goku #mawarrior...  0.534522  
2  #queenofworkouts #fitness #fitforHisreason #pr...  0.267261  
3  #teamfitcats #jujufitcats #teamshape #crossfit...  0.462910  
4  #legday #functionaltraining #bodybuilding #bod...  0.267261  
5  #HealthyEating #Stretches #BackStretches #Tota...  0.377964  
6   #INSANITY  #trustandbelievepod #twins #twinsa...  0.267261

## Critère 2 : Influenceurs qui présentent les intérêts d’un utilisateur u

In [403]:
#on récupère les # des influenceurs et on les stocke dans l'array corpus
corpus = []

i=0
while i<len(dataInfluencer):
    corpus.append(dataInfluencer["posts__caption"][i])
    i+=1

corpus



['#healthylifestyle #fitness #foodography #workout #fitfam #dietetique #diet #foodporn #fitnation #bodybuilders #mealprep #musculation',
 '#ma60day #momlife #childofGod #goku #mawarriorchallenge #mondaymotivation  #squatproof #transformationtuesday #fitness #fitfam #workoutmotivation #fitnessmotivation ',
 '#queenofworkouts #fitness #fitforHisreason #progress #homeworkout #fitgirl #dream #motivation #inspire #fitness #fullbody #gymworkout ',
 '#teamfitcats #jujufitcats #teamshape #crossfit #fitness #fitgirl #workout #fullbody #gymworkout #fitfam #motivation #fitnessmotivation ',
 '#legday #functionaltraining #bodybuilding #bodyweightworkout #fit #fitness#workout #JTMchallenge #abs #pushups #calisthenics #jtmfit',
 '#HealthyEating #Stretches #BackStretches #TotalBodyStretch #Stretching #WorkoutMotivation #Planks #AbChallenge #ChooseLunch #HealthyRecipes #fitness #fitgirl',
 ' #INSANITY  #trustandbelievepod #twins #twinsanity #parenting #dad #terribletwos #facts #fitness #fitnesslife #fi

In [320]:
vectorizer = CountVectorizer()
features = vectorizer.fit_transform(corpus).todense()
print(vectorizer.vocabulary_)

{'teamshape': 64, 'fitgirl': 20, 'fitness': 22, 'bodybuilders': 5, '4monthspostpartum': 0, 'healthylifestyle': 33, 'foodography': 25, 'workout': 71, 'fitfam': 18, 'dietetique': 14, 'diet': 13, 'foodporn': 26, 'fitnation': 21, 'mealprep': 45, 'musculation': 50, 'jeremyscottfitness': 38, 'health': 31, 'personaltrainer': 53, 'phoenix': 54, 'arizona': 3, 'menshealth': 46, 'onlinecoach': 51, 'workoutmotivation': 72, 'fitnessmotivation': 24, 'ma60day': 43, 'momlife': 47, 'childofgod': 9, 'goku': 29, 'mawarriorchallenge': 44, 'mondaymotivation': 48, 'squatproof': 59, 'transformationtuesday': 67, 'queenofworkouts': 58, 'fitforhisreason': 19, 'progress': 56, 'homeworkout': 35, 'dream': 15, 'motivation': 49, 'inspire': 37, 'fullbody': 27, 'gymworkout': 30, 'teamfitcats': 63, 'jujufitcats': 41, 'crossfit': 11, 'legday': 42, 'functionaltraining': 28, 'bodybuilding': 6, 'bodyweightworkout': 7, 'fit': 17, 'jtmchallenge': 39, 'abs': 2, 'pushups': 57, 'calisthenics': 8, 'jtmfit': 40, 'healthyeating': 

In [321]:
user = dataUser["posts__caption"] #on récupère les # de l'utilisateur
features1 = vectorizer.transform(user).todense()
print(features1)

[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0]]


In [322]:
print(euclidean_distances(features1[0],features))


[[8.42614977 3.60555128 3.87298335 3.87298335 3.87298335 3.60555128
  3.         3.87298335 3.60555128]]


In [323]:
print(cosine_similarity(features1[0],features))

[[0.05423261 0.25819889 0.23904572 0.12909944 0.23904572 0.25819889
  0.51639778 0.12909944 0.25819889]]


In [404]:
distances = cosine_similarity(features1[0],features)
#Après le calcul de la distance de similarité entre chaque influenceur et l'utilisateur u ,on ajoute cette distance au score
j=0
while j<len(dataInfluencer):
    dataInfluencer["Score"][j] += distances[0][j]
    j+=1
    

C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """


In [405]:
dataInfluencer.head(10)

alias           username  \
0         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   
1          MankoFit        massy.arias   
2      Alexia Clark       alexia_clark   
3   MAMAN FITCATS 🐱        jujufitcats   
4   Jay T. Maryniak            jtm_fit   
5  Jeanette Jenkins  msjeanettejenkins   
6           Shaun T             shaunt   

                                                 bio  followers__count  \
0  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
1                      Health coach @mawarriors CEO            2603731   
2  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
3  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
4  NEW YORK Creator of The Functional Method  I h...            566898   
5  Turn on post notifications 28yrs Experience Tr...            555090   
6  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
1  bayujovi2 beardedbarbellmaintenance kvillalba5...   
2  marti_m87 hatandhoopsfitness drlozanoorella ia...   
3  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
4  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
5  cbarbour3 alexanderfinley01 gergoerous_being b...   
6  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
0  #healthylifestyle #fitness #foodography #worko...  0.432197  
1  #ma60day #momlife #childofGod #goku #mawarrior...  0.792721  
2  #queenofworkouts #fitness #fitforHisreason #pr...  0.506307  
3  #teamfitcats #jujufitcats #teamshape #crossfit...  0.592009  
4  #legday #functionaltraining #bodybuilding #bod...  0.506307  
5  #HealthyEating #Stretches #BackStretches #Tota...  0.636163  
6   #INSANITY  #trustandbelievepod #twins #twinsa...  0.783659

## Critère 3 : Influenceurs avec le nombre de followers le plus élevé

### Calcul min et max followers__count

In [406]:
c=1
max = dataInfluencer["followers__count"][0]
min = dataInfluencer["followers__count"][0]
while c<len(dataInfluencer):
    if(dataInfluencer["followers__count"][c]>max):
        max = dataInfluencer["followers__count"][c]
    if(dataInfluencer["followers__count"][c]<min):
        min = dataInfluencer["followers__count"][c]    
    c+=1
    


### Calcul du taux de réputation de chaque influenceur 

In [407]:
i=0
while (i<len(dataInfluencer)):
    dataInfluencer["Score"][i] += (dataInfluencer["followers__count"][i]-min)/(max-min)
    i+=1

C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [408]:
dataInfluencer.head(10)


alias           username  \
0         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   
1          MankoFit        massy.arias   
2      Alexia Clark       alexia_clark   
3   MAMAN FITCATS 🐱        jujufitcats   
4   Jay T. Maryniak            jtm_fit   
5  Jeanette Jenkins  msjeanettejenkins   
6           Shaun T             shaunt   

                                                 bio  followers__count  \
0  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
1                      Health coach @mawarriors CEO            2603731   
2  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
3  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
4  NEW YORK Creator of The Functional Method  I h...            566898   
5  Turn on post notifications 28yrs Experience Tr...            555090   
6  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
1  bayujovi2 beardedbarbellmaintenance kvillalba5...   
2  marti_m87 hatandhoopsfitness drlozanoorella ia...   
3  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
4  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
5  cbarbour3 alexanderfinley01 gergoerous_being b...   
6  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
0  #healthylifestyle #fitness #foodography #worko...  0.432197  
1  #ma60day #momlife #childofGod #goku #mawarrior...  1.792721  
2  #queenofworkouts #fitness #fitforHisreason #pr...  1.215477  
3  #teamfitcats #jujufitcats #teamshape #crossfit...  1.078384  
4  #legday #functionaltraining #bodybuilding #bod...  0.709629  
5  #HealthyEating #Stretches #BackStretches #Tota...  0.834867  
6   #INSANITY  #trustandbelievepod #twins #twinsa...  1.120253

## Critère 4 : Influenceurs qui sont suivis par les amis de u

In [409]:
followingUser = dataUser["Following"] #on récupère la liste des amis de u
followingUser[0]

'nahawand_ghi eya_gandouz safe__kassrawi fekih.ahlem vyvisflavia tayechi.ameni micaarodriguez89 dayse_benicio safe_yahyaoui safa_khammouma abichousa andreideiu_ amrirym1 amina_banet_ha fatma.kb.1 amenibenhassan elliotbfit bouthainanaffati arwamarwani yazidisalma6 akremweslati zahrahotmani gypsydisaster.nyc belhassenhameda hadil_ben_younes hajer.ka jaabiriovic __m.saandy_ _gavpi safa_ouni sera__rez artur__fit lythi_nguyen hmaidi_syrine nourhene_ghorbeli hummer_aj tiboinshape chaymatab mariemomri4 sarablt5 areejjbnmabrouk_officielle sabrintbib nadra_khabir arwaoualleni souhameliene lagha.maram eya_yakdhane n.mou38 amoula_saghrouna bjaouimahee fashionweartoday maysounsozi eyamaatki taycyr_th imenechelly2 ti_an_dre ichrak_b_h _dafny1 raniahajji4 alisnoussi jlassi.ichrak sara_nasfi11 ayedi_feriel_ nasrallahracha wiem.trjm farah.tr ines_mahbouli maycengorai hend_arouri khammessy_maleek ghada_ben_mongi rania.hammemi mathlouthiab cyrine_mahjoubi nourhene.sekref nada_ryahi amira_nebli benmanaa.

In [410]:
#on parcoure la liste des followers de chaque influenceur à recommander et on calcule sa distance de similarité avec la 
#la liste d'amis de u 
distanceFollowers = []
vect = CountVectorizer()
k = []
k.append(followingUser[0])
feat = vect.fit_transform(k).todense()

index=0
followersInf = dataInfluencer["followers"]
while index<len(dataInfluencer):
    c = []
    c.append(followersInf[index])
    fea = vect.transform(c).todense()
    distanceFollowers.append(cosine_similarity(feat,fea))
    index+=1

In [411]:
distanceFollowers

[array([[0.10787198]]),
 array([[0.04472136]]),
 array([[0.07745967]]),
 array([[0.06324555]]),
 array([[0.06324555]]),
 array([[0.07745967]]),
 array([[0.]])]

In [412]:
# pour chaque influenceur on ajoute sa distance au score
c=0
while c<len(dataInfluencer):
    dataInfluencer["Score"][c] += distanceFollowers[c][0][0]
    c+=1

C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [413]:
dataInfluencer.head(10)

alias           username  \
0         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   
1          MankoFit        massy.arias   
2      Alexia Clark       alexia_clark   
3   MAMAN FITCATS 🐱        jujufitcats   
4   Jay T. Maryniak            jtm_fit   
5  Jeanette Jenkins  msjeanettejenkins   
6           Shaun T             shaunt   

                                                 bio  followers__count  \
0  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
1                      Health coach @mawarriors CEO            2603731   
2  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
3  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
4  NEW YORK Creator of The Functional Method  I h...            566898   
5  Turn on post notifications 28yrs Experience Tr...            555090   
6  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
1  bayujovi2 beardedbarbellmaintenance kvillalba5...   
2  marti_m87 hatandhoopsfitness drlozanoorella ia...   
3  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
4  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
5  cbarbour3 alexanderfinley01 gergoerous_being b...   
6  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
0  #healthylifestyle #fitness #foodography #worko...  0.540069  
1  #ma60day #momlife #childofGod #goku #mawarrior...  1.837443  
2  #queenofworkouts #fitness #fitforHisreason #pr...  1.292937  
3  #teamfitcats #jujufitcats #teamshape #crossfit...  1.141629  
4  #legday #functionaltraining #bodybuilding #bod...  0.772875  
5  #HealthyEating #Stretches #BackStretches #Tota...  0.912327  
6   #INSANITY  #trustandbelievepod #twins #twinsa...  1.120253

# Score final

In [414]:
#pour chaque influenceur On divise son score par 4
c=0
while c<len(dataInfluencer):
    dataInfluencer["Score"][c]=dataInfluencer["Score"][c]/4
    c+=1

C:\Users\iheb_\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [415]:
dataInfluencer.head(10)

alias           username  \
0         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   
1          MankoFit        massy.arias   
2      Alexia Clark       alexia_clark   
3   MAMAN FITCATS 🐱        jujufitcats   
4   Jay T. Maryniak            jtm_fit   
5  Jeanette Jenkins  msjeanettejenkins   
6           Shaun T             shaunt   

                                                 bio  followers__count  \
0  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   
1                      Health coach @mawarriors CEO            2603731   
2  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
3  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
4  NEW YORK Creator of The Functional Method  I h...            566898   
5  Turn on post notifications 28yrs Experience Tr...            555090   
6  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   

                                           followers  \
0  onsamira nesrine_nheri najeh294 eyarahal12345 ...   
1  bayujovi2 beardedbarbellmaintenance kvillalba5...   
2  marti_m87 hatandhoopsfitness drlozanoorella ia...   
3  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
4  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
5  cbarbour3 alexanderfinley01 gergoerous_being b...   
6  crharrin karshpreet143 assia_el_hidaya lulamac...   

                                      posts__caption     Score  
0  #healthylifestyle #fitness #foodography #worko...  0.135017  
1  #ma60day #momlife #childofGod #goku #mawarrior...  0.459361  
2  #queenofworkouts #fitness #fitforHisreason #pr...  0.323234  
3  #teamfitcats #jujufitcats #teamshape #crossfit...  0.285407  
4  #legday #functionaltraining #bodybuilding #bod...  0.193219  
5  #HealthyEating #Stretches #BackStretches #Tota...  0.228082  
6   #INSANITY  #trustandbelievepod #twins #twinsa...  0.280063

In [422]:
dataInfluencer.sort_values(by=['Score'], ascending=False,inplace=True) #tri de dataset selon score

In [423]:
#mise à jour des indices de dataset
i=0 
index = []
while i<len(dataInfluencer):
    index.append(i)
    i+=1
    
dataInfluencer.set_index([pd.Index(index)],inplace=True)

In [424]:
dataInfluencer

alias           username  \
0          MankoFit        massy.arias   
1      Alexia Clark       alexia_clark   
2   MAMAN FITCATS 🐱        jujufitcats   
3           Shaun T             shaunt   
4  Jeanette Jenkins  msjeanettejenkins   
5   Jay T. Maryniak            jtm_fit   
6         𝗔 𝗬 𝗢 𝗨 𝗕       ayoub_dhouib   

                                                 bio  followers__count  \
0                      Health coach @mawarriors CEO            2603731   
1  👑Queen Of Workouts👑\nFit for His reason🙏🏼\nCer...           1860178   
2  Crossfit. Health. Self-Love.\n🏆 1st Bikini NFS...           1290565   
3  Let’s TRANSFORM YOUR LIFE Family Man Fitness M...            907629   
4  Turn on post notifications 28yrs Experience Tr...            555090   
5  NEW YORK Creator of The Functional Method  I h...            566898   
6  •Pilot\n•Youtuber\n•Model with @jaromanagement...             47072   

                                           followers  \
0  bayujovi2 beardedbarbellmaintenance kvillalba5...   
1  marti_m87 hatandhoopsfitness drlozanoorella ia...   
2  felicia95014 lisaa_hgl namedmatteo 2007louanne...   
3  crharrin karshpreet143 assia_el_hidaya lulamac...   
4  cbarbour3 alexanderfinley01 gergoerous_being b...   
5  _jamesnorman sasha_prokopiev ang_guz_ kooffeey...   
6  onsamira nesrine_nheri najeh294 eyarahal12345 ...   

                                      posts__caption     Score  
0  #ma60day #momlife #childofGod #goku #mawarrior...  0.459361  
1  #queenofworkouts #fitness #fitforHisreason #pr...  0.323234  
2  #teamfitcats #jujufitcats #teamshape #crossfit...  0.285407  
3   #INSANITY  #trustandbelievepod #twins #twinsa...  0.280063  
4  #HealthyEating #Stretches #BackStretches #Tota...  0.228082  
5  #legday #functionaltraining #bodybuilding #bod...  0.193219  
6  #healthylifestyle #fitness #foodography #worko...  0.135017